# Generated by Django 6.1.1 on 2026-09-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_slug', models.SlugField(max_length=64)),
                ('agency_name', models.CharField(max_length=160)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('probed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('unreachable', 'unreachable'), ('http_error', 'http error'), ('blocked', 'blocked'), ('captcha', 'captcha'), ('no_listings', 'no listings')], default='ok', max_length=16)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('final_url', models.URLField(blank=True, max_length=400)),
                ('note', models.TextField(blank=True)),
                ('platform', models.CharField(blank=True, max_length=120)),
                ('server', models.CharField(blank=True, max_length=120)),
                ('meta_charset', models.CharField(blank=True, max_length=32)),
                ('header_charset', models.CharField(blank=True, max_length=32)),
                ('robots_found', models.BooleanField(default=False)),
                ('robots_disallow', models.JSONField(blank=True, default=list)),
                ('robots_blocks_listings', models.BooleanField(default=False)),
                ('sitemaps', models.JSONField(blank=True, default=list)),
                ('sitemap_url_count', models.IntegerField(blank=True, null=True)),
                ('url_shapes', models.JSONField(blank=True, default=list)),
                ('listing_pattern', models.CharField(blank=True, max_length=200)),
                ('listing_count', models.IntegerField(blank=True, null=True)),
                ('wp_types', models.JSONField(blank=True, default=dict)),
                ('has_project_pages', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ['agency_slug', '-probed_at'],
                'get_latest_by': 'probed_at',
            },
        ),
    ]
