# Generated by Django 6.1.1 on 2026-09-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprobe',
            name='catalogue_patterns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
