# Generated by Django 6.1.1 on 2026-09-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_siteprobe_catalogue_patterns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteprobe',
            options={'get_latest_by': 'run_started', 'ordering': ['agency_slug', '-run_started', '-probed_at']},
        ),
        migrations.AddField(
            model_name='siteprobe',
            name='run_id',
            field=models.CharField(db_index=True, default='legacy', max_length=12),
        ),
        migrations.AddField(
            model_name='siteprobe',
            name='run_started',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='siteprobe',
            index=models.Index(fields=['-run_started', 'agency_slug'], name='market_site_run_sta_17978b_idx'),
        ),
    ]
