# Generated by Django 6.1.1 on 2026-09-25 18:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_siteprobe_options_siteprobe_run_id_and_more'),
        ('sourcing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name_bg', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='market.country')),
            ],
            options={
                'ordering': ['name_bg'],
            },
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name_bg', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neighbourhoods', to='market.city')),
            ],
            options={
                'ordering': ['name_bg'],
            },
        ),
        migrations.CreateModel(
            name='NeighbourhoodAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=160)),
                ('normalized_alias', models.CharField(db_index=True, editable=False, max_length=160)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='market.neighbourhood')),
            ],
        ),
        migrations.CreateModel(
            name='OfferGeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_location', models.TextField(blank=True)),
                ('normalized_location', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('matched_by', models.CharField(default='unresolved', max_length=40)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_geographies', to='market.city')),
                ('neighbourhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_geographies', to='market.neighbourhood')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo', to='sourcing.offer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='neighbourhood',
            constraint=models.UniqueConstraint(fields=('city', 'slug'), name='neighbourhood_city_slug'),
        ),
        migrations.AddConstraint(
            model_name='neighbourhoodalias',
            constraint=models.UniqueConstraint(fields=('neighbourhood', 'normalized_alias'), name='neighbourhood_alias_unique'),
        ),
        migrations.AddIndex(
            model_name='offergeo',
            index=models.Index(fields=['city', 'neighbourhood'], name='offer_geo_city_neigh_idx'),
        ),
        migrations.AddConstraint(
            model_name='offergeo',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='offer_geo_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='offergeo',
            constraint=models.CheckConstraint(condition=models.Q(('neighbourhood__isnull', True), ('city__isnull', False), _connector='OR'), name='offer_geo_neigh_has_city'),
        ),
    ]
