# Generated by Django 6.1.1 on 2026-09-25 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_seed_geography_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprobe',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_probes', to='market.city'),
        ),
        migrations.AddField(
            model_name='siteprobe',
            name='strategy',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
