# -*- coding: utf-8 -*-
"""Render docs/crawl-map.md from the latest SiteProbe per agency.

The crawl map is the contract between reconnaissance and phase 3: a recipe may
only be written for a row whose listing pattern was verified against a live
page. Everything else is recorded with the reason it cannot be crawled, so an
agency is never silently dropped and never silently guessed at.
"""
from django.core.management.base import BaseCommand

from market import agencies_varna
from market.models import SiteProbe

STATUS_ICON = {
    'ok': '✅', 'no_listings': '🟡', 'blocked': '⛔',
    'captcha': '🧩', 'http_error': '⚠️', 'unreachable': '❌',
}


class Command(BaseCommand):
    help = 'Write docs/crawl-map.md from the latest probes.'

    def handle(self, *args, **options):
        from django.conf import settings
        # Ordered by when each sweep STARTED, not when its rows landed, so a
        # superseded run that finished late cannot reinstate its results.
        latest = SiteProbe.latest()

        registry = {r['slug']: r for r in agencies_varna.rows()}
        rows = [latest[s] for s in sorted(latest)]
        # A pattern backed by a handful of URLs is a hypothesis that happened to
        # survive one fetch. Below this, a human opens the site before a recipe
        # is written -- which is what phase 2's verification step actually means.
        CONFIDENT = 20
        crawlable = [p for p in rows if p.crawlable and (p.listing_count or 0) >= CONFIDENT]
        thin = [p for p in rows if p.crawlable and (p.listing_count or 0) < CONFIDENT]
        stock = sum(p.listing_count or 0 for p in crawlable)
        probed_on = max((p.probed_at for p in rows), default=None)

        out = [
            '# Crawl map — Varna\n',
            'Generated by `python manage.py crawl_map` from the latest `SiteProbe` '
            'per agency. Do not edit by hand.\n',
            f'Reconnaissance: **{probed_on:%d.%m.%Y}**  ·  '
            f'Agencies admitted: **{len(registry)}**  ·  '
            f'Probed: **{len(rows)}**  ·  Crawlable: **{len(crawlable)}**  ·  '
            f'Listing URLs discovered: **~{stock:,}**\n',
            f'Ready to crawl now: **{len(crawlable)}** agencies. '
            f'Needing a human look first: **{len(thin)}**.\n',
            '> **Rule 7.** Every listing pattern below was accepted only after a real\n'
            '> page behind it was fetched and found to be priced and measured. A shape\n'
            '> that no live page confirmed is not recorded as a pattern, however\n'
            '> plausible it looked. A previous scraper in this family was written\n'
            '> against `/realestates/newdev`, which 404s, and another parsed a news\n'
            '> feed — both looked right and stored nothing.\n',
            '## Crawlable\n',
            '| | agency | platform | listing pattern | urls | project pages | charset |',
            '|---|---|---|---|---:|---|---|',
        ]
        for p in crawlable:
            out.append(
                f'| {STATUS_ICON[p.status]} | [{p.agency_name}]({p.website}) '
                f'| {p.platform or "custom"} | `{p.listing_pattern}` '
                f'| {p.listing_count or "?"} '
                f'| {"yes" if p.has_project_pages else "—"} '
                f'| {p.meta_charset or p.header_charset or "?"} |')

        if thin:
            out += ['\n## Needs manual confirmation\n',
                    'A live page behind each of these patterns came back looking like a '
                    'property, but on too few URLs to trust the shape. Open the site '
                    'before writing a recipe — this is the row where the previous '
                    'Bulgarian Properties scraper went wrong.\n',
                    '| agency | platform | candidate pattern | urls | evidence |',
                    '|---|---|---|---:|---|']
            for p in thin:
                out.append(f'| [{p.agency_name}]({p.website}) | {p.platform or "custom"} '
                           f'| `{p.listing_pattern}` | {p.listing_count or "?"} '
                           f'| {(p.note or "")[:200]} |')

        blocked = [p for p in rows if not p.crawlable]
        if blocked:
            out += ['\n## Not crawlable yet\n',
                    'Recorded rather than dropped. Each is a reason, and several are '
                    'the first calls to make when the API conversation starts.\n',
                    '| | agency | status | what we found |', '|---|---|---|---|']
            for p in blocked:
                why = (p.note or '').strip() or f'HTTP {p.http_status}'
                out.append(f'| {STATUS_ICON[p.status]} | [{p.agency_name}]({p.website}) '
                           f'| {p.status} | {why[:240]} |')

        missing = agencies_varna.unverified()
        if missing:
            out += ['\n## Website not found\n',
                    'Admitted on association membership or record, but with no site '
                    'of their own located yet. They list through portals, which we do '
                    'not crawl.\n']
            for r in missing:
                out.append(f'- **{r["name"]}** — {r["admission_basis"]}'
                           + (f'. {r["note"]}' if r['note'] else ''))

        out += ['\n## robots.txt — recorded, not obeyed\n',
                'See `docs/CRAWL-POLICY.md`. This table is also the API-negotiation '
                'call sheet: an agency that explicitly disallowed crawling is the '
                'first conversation to have.\n',
                '| agency | robots.txt | disallows listings | rules |',
                '|---|---|---|---:|']
        for p in rows:
            if p.robots_found:
                out.append(f'| {p.agency_name} | found '
                           f'| {"**yes**" if p.robots_blocks_listings else "no"} '
                           f'| {len(p.robots_disallow or [])} |')

        out += ['\n## Excluded agencies\n',
                'Not an oversight. The exclusion list is published because the claim '
                'the product rests on is that we vet supply.\n']
        for slug, reason in sorted(agencies_varna.EXCLUDED.items()):
            out.append(f'- **{slug}** — {reason}')

        path = settings.BASE_DIR / 'docs' / 'crawl-map.md'
        path.write_text('\n'.join(out) + '\n', encoding='utf-8')
        self.stdout.write(self.style.SUCCESS(
            f'Wrote {path.relative_to(settings.BASE_DIR)} — '
            f'{len(crawlable)} crawlable, ~{stock:,} listing URLs'))
