# -*- coding: utf-8 -*-
"""Turn a crawl trace into the map: what worked, what did not, what it cost.

The first crawl of a market is a measurement exercise. This reads the JSONL
trace `crawl_varna` writes and answers the questions that decide how the second
crawl should be run differently:

  * which agencies are worth their request budget, and which are all archive;
  * which fields the extractor misses on which sites -- a site with no area on
    every page needs a recipe hint, and that looks identical to a site whose
    listings genuinely have no area unless you count per field per agency;
  * where the time and bytes actually went;
  * how much of each sitemap is stale, which is the number that decides
    sitemap-versus-catalogue per site from tomorrow on.
"""
import json
from collections import defaultdict

from django.conf import settings
from django.core.management.base import BaseCommand

from sourcing.models import CrawlRun, Offer, OfferImage, OfferSource

TRACKED = ('price_eur', 'area_m2', 'bedrooms', 'floor', 'location',
           'property_kind', 'deal_type', 'title')


class Command(BaseCommand):
    help = 'Write docs/crawl-report-<date>.md from a crawl trace.'

    def add_arguments(self, parser):
        parser.add_argument('--run', type=int, help='CrawlRun id (default: latest)')

    def handle(self, *args, **options):
        run = (CrawlRun.objects.filter(pk=options['run']).first() if options['run']
               else CrawlRun.objects.filter(kind='sites').order_by('-pk').first())
        if run is None:
            self.stdout.write(self.style.ERROR('No crawl run found.'))
            return

        trace_path = next(settings.RUNS_DIR.glob(f'crawl-*-{run.pk}.jsonl'), None)
        rows = []
        if trace_path and trace_path.exists():
            for line in trace_path.open(encoding='utf-8'):
                try:
                    rows.append(json.loads(line))
                except ValueError:
                    continue

        per = defaultdict(lambda: defaultdict(int))
        fields = defaultdict(lambda: defaultdict(int))
        statuses = defaultdict(lambda: defaultdict(int))
        ms = defaultdict(list)
        for row in rows:
            agency = row.get('agency', '?')
            per[agency][row.get('outcome', '?')] += 1
            per[agency]['bytes'] += row.get('bytes', 0)
            per[agency]['urls'] += 1
            statuses[agency][str(row.get('status'))] += 1
            if row.get('ms'):
                ms[agency].append(row['ms'])
            for field in row.get('fields_found', []):
                fields[agency][field] += 1
            if row.get('image', '').startswith('none'):
                per[agency]['image_missing'] += 1
            elif row.get('image'):
                per[agency]['image_ok'] += 1
            if row.get('listing_status') in ('sold', 'reserved'):
                per[agency]['sold'] += 1

        out = [f'# Crawl report — run #{run.pk}\n',
               'Generated by `python manage.py crawl_report`. Do not edit by hand.\n',
               f'Started **{run.run_date}**  ·  status **{run.status}**  ·  '
               f'URLs traced **{len(rows):,}**\n',
               '## Per agency\n',
               '| agency | urls | stored | failed | main image | sold/res. | MB | median ms |',
               '|---|---:|---:|---:|---:|---:|---:|---:|']
        for agency in sorted(per):
            p = per[agency]
            stored = p['new'] + p['changed'] + p['same']
            times = sorted(ms[agency])
            median = times[len(times) // 2] if times else 0
            out.append(
                f'| {agency} | {p["urls"]:,} | {stored:,} | '
                f'{p["fetch_failed"] + p["extract_none"] + p["extract_error"]:,} '
                f'| {p["image_ok"]:,} | {p["sold"]:,} '
                f'| {p["bytes"] / 1e6:.0f} | {median:,} |')

        out += ['\n## Field fill rates\n',
                'A field missing on every page of one site is a recipe problem. A field '
                'missing on a few is just an agency that did not publish it. Only a '
                'per-agency breakdown tells them apart.\n',
                '| agency | ' + ' | '.join(TRACKED) + ' |',
                '|---|' + '---:|' * len(TRACKED)]
        for agency in sorted(fields):
            stored = per[agency]['new'] + per[agency]['changed'] + per[agency]['same']
            if not stored:
                continue
            cells = []
            for field in TRACKED:
                pct = 100 * fields[agency][field] / stored
                mark = '' if pct >= 80 else (' ⚠️' if pct >= 20 else ' ❌')
                cells.append(f'{pct:.0f}%{mark}')
            out.append(f'| {agency} | ' + ' | '.join(cells) + ' |')

        out += ['\n## HTTP statuses\n', '| agency | ' + ' | '.join(
            sorted({s for a in statuses for s in statuses[a]})) + ' |']
        codes = sorted({s for a in statuses for s in statuses[a]})
        out.append('|---|' + '---:|' * len(codes))
        for agency in sorted(statuses):
            out.append(f'| {agency} | '
                       + ' | '.join(str(statuses[agency].get(c, 0)) for c in codes) + ' |')

        # What the database actually holds now, independent of the trace.
        out += ['\n## What is stored\n',
                f'- Active offers: **{Offer.objects.filter(is_active=True).count():,}**',
                f'- Offers with a main image: '
                f'**{OfferImage.objects.values("offer").distinct().count():,}**',
                f'- Distinct image hashes: '
                f'**{OfferImage.objects.values("sha256").distinct().count():,}** '
                f'— a hash shared across agencies is phase 5b evidence that two '
                f'listings are the same building.']

        out += ['\n## What to change before the next run\n',
                'Filled in by hand after reading the tables above. The point of a first '
                'crawl is that the second one is cheaper.\n']

        path = settings.BASE_DIR / 'docs' / f'crawl-report-{run.run_date}.md'
        path.write_text('\n'.join(out) + '\n', encoding='utf-8')
        self.stdout.write(self.style.SUCCESS(
            f'Wrote {path.relative_to(settings.BASE_DIR)} from {len(rows):,} traced URLs'))
