/* Run against a local preview or the deployed app. Playwright is optional tooling. */
const assert = require('node:assert/strict')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const base = process.env.BUYER_SMOKE_URL || 'http://127.0.0.1:8420'

;(async () => {
  const browser = await chromium.launch({ headless: true })
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } })
    const page = await context.newPage()
    const errors = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto(`${base}/for-you?city=sofia`)
    await page.getByRole('heading', { name: 'Първо ни кажи какво търсиш' }).waitFor()
    await page.getByRole('link', { name: 'Попълни профила' }).click()
    const form = page.locator('form.buyer-layout')
    await form.getByLabel('Град', { exact: true }).selectOption('sofia')
    await form.getByLabel('Брой стаи', { exact: true }).selectOption('2')
    await form.getByLabel('Бюджет от (€)', { exact: true }).fill('80000')
    await form.getByLabel('Бюджет до (€)', { exact: true }).fill('200000')
    await form.getByLabel('Лозенец', { exact: true }).check()
    await form.getByLabel('Младост 1', { exact: true }).check()
    await form.getByLabel('Домакинство / семейно положение', { exact: true }).selectOption('family')
    await form.getByLabel('Деца', { exact: true }).selectOption('1')
    await form.getByLabel('Домашни любимци', { exact: true }).selectOption('cat')
    await form.getByLabel('Асансьор', { exact: true }).check()
    await page.getByRole('button', { name: 'Запази и виж офертите за теб' }).click()
    await page.waitForURL(/\/for-you/)
    await page.locator('.buyer-match-card').or(page.getByRole('heading', { name: 'Все още няма подходящи оферти' })).first().waitFor()
    const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('pb3.buyer.profile.v1')))
    assert.equal(saved.city, 'sofia')
    assert.equal(saved.rooms, '2')
    assert.equal(saved.family, 'family')
    assert.equal(saved.pets, 'cat')
    assert.deepEqual(saved.neighbourhoods.sort(), ['lozenets', 'mladost-1'])
    await page.reload()
    await page.locator('.buyer-match-card').or(page.getByRole('heading', { name: 'Все още няма подходящи оферти' })).first().waitFor()
    await page.getByRole('link', { name: 'Редактирай профила' }).click()
    assert.equal(await form.getByLabel('Домашни любимци', { exact: true }).inputValue(), 'cat')
    assert.equal(await form.getByLabel('Домакинство / семейно положение', { exact: true }).inputValue(), 'family')
    await form.getByLabel('Град', { exact: true }).selectOption('varna')
    await page.waitForURL(/city=varna/)
    await form.getByLabel('Бюджет от (€)', { exact: true }).fill('')
    await form.getByLabel('Бюджет до (€)', { exact: true }).fill('')
    await form.getByLabel('Асансьор', { exact: true }).uncheck()
    await form.getByLabel('Домашни любимци', { exact: true }).selectOption('none')
    await page.getByRole('button', { name: 'Запази и виж офертите за теб' }).click()
    await page.waitForURL(/\/for-you.*city=varna/)
    await page.locator('.buyer-match-card .offer').first().waitFor()
    const matches = await page.locator('.buyer-match-card').count()
    assert(matches > 0)
    await page.getByRole('button', { name: 'Добави в желани', exact: true }).first().click()
    await page.getByRole('link', { name: /Желани имоти/ }).click()
    await page.getByRole('heading', { name: 'Желани имоти · 1' }).waitFor()
    await page.locator('.offer').first().waitFor()
    await page.reload()
    await page.locator('.offer').first().waitFor()
    await page.getByRole('button', { name: 'Премахни от желани', exact: true }).click()
    await page.getByRole('heading', { name: 'Запази първия си имот' }).waitFor()
    await page.getByRole('link', { name: 'Оферти', exact: true }).click()
    await page.locator('.offer').first().waitFor()
    await page.getByRole('button', { name: 'Добави в желани', exact: true }).first().click()
    await page.locator('.offer').first().click()
    await page.locator('.detail-specs').waitFor()
    await page.getByRole('button', { name: 'Премахни от желани', exact: true }).click()
    await page.getByRole('button', { name: 'Добави в желани', exact: true }).click()
    await page.getByRole('link', { name: /Желани имоти/ }).click()
    await page.locator('.offer').first().waitFor()

    // Unavailable entries remain removable rather than disappearing silently.
    await page.evaluate(() => localStorage.setItem('pb3.buyer.wishlist.v1', JSON.stringify([
      { id: Number.MAX_SAFE_INTEGER, title: 'Unavailable smoke-test property' },
    ])))
    await page.reload()
    await page.getByText('Тази оферта вече не е активна или не е налична.', { exact: false }).waitFor()
    await page.getByRole('button', { name: 'Премахни от желани', exact: true }).click()
    await page.getByRole('heading', { name: 'Запази първия си имот' }).waitFor()
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto(`${base}/user?city=sofia`)
    await form.waitFor()
    assert.equal(await form.getByLabel('Град', { exact: true }).inputValue(), 'sofia')
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
    await page.screenshot({ path: '/tmp/pb-buyer-mobile.png', fullPage: true })

    // Storage failures must not pretend a profile was saved or navigate away.
    await page.evaluate(() => { Storage.prototype.setItem = () => { throw new Error('storage disabled') } })
    await page.getByRole('button', { name: 'Запази и виж офертите за теб' }).click()
    await page.getByText('Браузърът не позволява запазване.', { exact: false }).waitFor()
    assert.match(page.url(), /\/user/)
    assert.deepEqual(errors, [])
    console.log(JSON.stringify({ status: 'passed', base, visibleMatches: matches,
      checks: ['Sofia profile', 'multiple neighbourhoods', 'household and pets', 'saved profile reload',
        'Varna matches', 'wishlist add/remove/reload', 'search and detail wishlist',
        'unavailable wishlist entries', 'mobile layout', 'storage failure', 'no runtime errors'] }))
  } finally { await browser.close() }
})().catch((error) => { console.error(error); process.exitCode = 1 })
