# -*- coding: utf-8 -*-
"""The second vendoring hop, and the machinery that keeps it honest.

seaside-monitor  --hop 1-->  broker-crm/sourcing/vendor  --hop 2-->  here

Hop 1 is guarded inside the vendored tree itself, by the manifest at
sourcing/vendor/UPSTREAM.md and the tests beside it. Those files arrived here
untouched and that guard still works, unchanged.

Hop 2 is this module. broker-crm solved multi-agency ingest, identity and
dedupe for one Burgas brokerage; this project reuses that work for a public
Varna market. Copying is the honest description of what happened, so the copy
is recorded rather than quietly forked: every file below is checksummed against
its origin, and a file that drifts must be declared a DIVERGENCE with a reason.

The point is not to freeze the code. It is that in six months, "did we change
this or did broker-crm?" must be answerable in one command:

    python manage.py vendor_check      # is the copy still what we recorded?
    python manage.py vendor_record     # re-record after a deliberate change
"""
import hashlib
import re
from pathlib import Path

from django.conf import settings

UPSTREAM_ROOT = Path('/Users/gabe/Dev/broker-crm')
MANIFEST = Path(settings.BASE_DIR) / 'docs' / 'VENDOR-MANIFEST.md'

# local path under this repo  ->  path under broker-crm
VENDORED = {
    'sourcing': 'sourcing',
    'crm/dedup.py': 'crm/dedup.py',
    'crm/features.py': 'crm/features.py',
    'crm/geo.py': 'crm/geo.py',
}

# Files the copy brings along that are not ours to keep or not wanted here.
# Excluded from the manifest so they are never treated as vendored code.
EXCLUDE = (
    'migrations/',          # regenerated against this database
    '__pycache__/',
    'crm/__init__.py',   # ours: a docstring, no upstream original
    'assets/',              # broker-crm's client's own partner registry
    'data/agencies.json',   # ditto
    '.pyc',
)

# path -> why it deliberately differs from upstream. Anything listed here is
# checked for *presence*, not for byte-identity.
DIVERGENCES = {
    'crm/dedup.py':
        'Multi-city expansion: fuzzy candidates must share a resolved OfferGeo '
        'city with the reference offer. Stored dedup keys and supply identity '
        'are unchanged; unresolved city cannot produce siblings.',
    'sourcing/web/fetch.py':
        "Upstream hardcodes the user agent 'BrokerCRM/1.0 "
        "(+https://bg-apartment.com)'. Shipping that would identify our crawler "
        "as a different project and send webmaster complaints to someone else's "
        "site. Reads CRAWL_USER_AGENT_BOT and CRAWL_HOST_DELAY from settings "
        "instead. Nothing else in the file is changed.",
}


def _digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def _lines(path):
    return len(path.read_text(encoding='utf-8', errors='replace').splitlines())


def local_files():
    """Every vendored file in this repo, as repo-relative posix paths."""
    base = Path(settings.BASE_DIR)
    out = []
    for local in VENDORED:
        target = base / local
        candidates = sorted(target.rglob('*')) if target.is_dir() else [target]
        for path in candidates:
            if not path.is_file():
                continue
            rel = path.relative_to(base).as_posix()
            if any(token in rel for token in EXCLUDE):
                continue
            out.append(rel)
    return sorted(out)


def upstream_path(rel):
    """Where `rel` came from in broker-crm, or None if it is ours alone."""
    for local, remote in VENDORED.items():
        if rel == local:
            return UPSTREAM_ROOT / remote
        if rel.startswith(local.rstrip('/') + '/'):
            return UPSTREAM_ROOT / remote / rel[len(local) + 1:]
    return None


def build_rows():
    base = Path(settings.BASE_DIR)
    rows = []
    for rel in local_files():
        path = base / rel
        origin = upstream_path(rel)
        rows.append({
            'path': rel,
            'lines': _lines(path),
            'digest': _digest(path),
            'origin': origin.relative_to(UPSTREAM_ROOT).as_posix() if origin else '',
            'diverged': rel in DIVERGENCES,
        })
    return rows


def render_manifest(rows):
    head = (
        '# Vendor manifest — hop 2 (broker-crm → varna-market)\n\n'
        'Generated by `python manage.py vendor_record`. Do not edit by hand.\n\n'
        f'Upstream: `{UPSTREAM_ROOT}`  \n'
        f'Files: **{len(rows)}**  ·  Lines: **{sum(r["lines"] for r in rows):,}**\n\n'
        'A checksum here is a claim that this file is byte-identical to the\n'
        'broker-crm file it names. `manage.py vendor_check` fails when that\n'
        'stops being true, so a fork has to be a decision rather than a drift.\n\n'
        '| file | lines | sha256:16 | from broker-crm |\n'
        '|---|---:|---|---|\n'
    )
    body = ''.join(
        f'| `{r["path"]}` | {r["lines"]} | `{r["digest"]}` | `{r["origin"]}` |\n'
        for r in rows)
    tail = ''
    if DIVERGENCES:
        tail = ('\n## Declared divergences\n\n'
                'These files were changed on purpose. Each needs a reason.\n\n'
                '| file | why |\n|---|---|\n' +
                ''.join(f'| `{k}` | {v} |\n' for k, v in sorted(DIVERGENCES.items())))
    return head + body + tail


def manifest_rows():
    """Parse the committed manifest back into {path: (lines, digest, origin)}."""
    if not MANIFEST.exists():
        return {}
    found = re.findall(
        r'^\| `([^`]+)` \| (\d+) \| `([0-9a-f]+)` \| `([^`]*)` \|$',
        MANIFEST.read_text(encoding='utf-8'), re.M)
    return {p: (int(n), d, o) for p, n, d, o in found}


def compare():
    """Three lists: files that drifted, files missing, files not in the manifest."""
    base = Path(settings.BASE_DIR)
    recorded = manifest_rows()
    current = {r['path']: r for r in build_rows()}

    drifted, missing = [], []
    for path, (lines, digest, _origin) in recorded.items():
        if path in DIVERGENCES:
            if not (base / path).exists():
                missing.append(path)
            continue
        row = current.get(path)
        if row is None:
            missing.append(path)
        elif row['digest'] != digest or row['lines'] != lines:
            drifted.append(path)
    unrecorded = sorted(set(current) - set(recorded))
    return drifted, missing, unrecorded


def upstream_drift():
    """Files broker-crm has changed since we copied them.

    Not a failure. This is the 'what did they fix that we should take?' list,
    and it is the only reason the origin column is worth carrying.
    """
    base = Path(settings.BASE_DIR)
    out = []
    for rel in local_files():
        origin = upstream_path(rel)
        if origin is None:
            continue
        if not origin.exists():
            out.append((rel, 'gone upstream'))
        elif _digest(origin) != _digest(base / rel):
            out.append((rel, 'changed upstream'))
    return out
